# Generated by Django 2.2.6 on 2020-05-03 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_auto_20200503_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion', models.NullBooleanField(default=None, verbose_name='Чтение завершено')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_book', to='p_library.Book', verbose_name='Книга')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor_friend', to='p_library.Friend', verbose_name='должник')),
            ],
            options={
                'verbose_name': 'одолженная книга',
                'verbose_name_plural': 'одолженные книги',
            },
        ),
        migrations.DeleteModel(
            name='BookReading',
        ),
    ]
