# Generated by Django 2.2.6 on 2020-05-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_book_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, upload_to='covers/', verbose_name='Картинка'),
        ),
    ]
